### ISSUE TITLE
Richiesta di aggiunta dati

### ISSUE THREAD

**Issue by Lukemoro01** [savio-99/territoryeditor-release#10]
Richiesta di poter visualizzare tramite indicazione numerica il numero di territori attualmente assegnati. è possibile ricavare il dato dalla sezione assegnazioni, ma non fornisce un dato numerico ed è difficile ottenere un numero preciso dal grafico.

**Comment by savio-99** [comment]
Solo perché sei tu **non** la inserisco

**Comment by Lukemoro01** [comment]
Non perché sono io, ma perché alcuni utilizzatori dell'app ritengono possa
essere utile per capire quanti territori stanno percorrendo i proclamatori.
Utile soprattutto in congregazioni che hanno molti territori

Il ven 7 gen 2022, 18:03 savio-99 ***@***.***> ha scritto:

**Comment by savio-99** [comment]
Funzione aggiunta nella [v1.5.0](https://github.com/savio-99/territoryeditor-release/releases/tag/v1.5.0)
