### ISSUE TITLE
App Mobile - Visualizzazione territori in giacenza

### ISSUE THREAD

**Issue by Lukemoro01** [savio-99/territoryeditor-release#14]
Sarebbe comodo visualizzare oltre al numero del territorio anche il comune di appartenenza, in modo da poterli identificare nel caso di assegnazioni solo numeriche come da foto
![photo_2022-06-26_19-22-19](https://user-images.githubusercontent.com/53223843/175826290-e38355bd-dd43-4a8c-8fc3-3185677b140e.jpg)

**Comment by savio-99** [comment]
Fix in versione app 1.0.3
