### ISSUE TITLE
Modifica della data in linea

### ISSUE THREAD

**Issue by Lukemoro01** [savio-99/territoryeditor-release#2]
Rendere possibile aggiungere o modificare la data della registrazione direttamente in linea invece che dover usare necessariamente il riquadro del calendario

**Comment by savio-99** [comment]
È già possibile modificare il testo nelle caselle di testo con calendario

**Comment by Lukemoro01** [comment]
No, non funziona. se modifichi la data scrivendo a mano e poi fai salva non
memorizza il dato


Il giorno ven 3 set 2021 alle ore 11:10 savio-99 ***@***.***>
ha scritto:

**Comment by savio-99** [comment]
Risolto nella v1.3.3
