### ISSUE TITLE
App mobile - Utilizzo su IOS

### ISSUE THREAD

**Issue by Lukemoro01** [savio-99/territoryeditor-release#25]
Sulla wiki non ho trovato la guida su come installare l'app mobile su un dispositivo IoS. 
Provando tramite app Expo come indicato però non funziona

**Comment by savio-99** [comment]
Una volta scaricata l'app Expo Go sul dispositivo aprire il [questo link](https://expo.dev/@lucafenner/territoryeditor-mobile). Una volta aperto cliccare su Open in Expo Go.
In alternativa è possibile aprire il link su un computer e scansionare il QR tramite app Expo Go.

**Comment by Lukemoro01** [comment]
![IMG_20220901_220131](https://user-images.githubusercontent.com/53223843/188067422-b2522eaf-4530-44bb-a356-fac34c5625a7.jpg)
Dopo aver provato su 3 dispositivi iOS diversi, tra tablet e telefono compresi tra i 5 e 2 anni di produzione, appare in tutti questo errore
