### ISSUE TITLE
App mobile - giacenze

### ISSUE THREAD

**Issue by Lukemoro01** [savio-99/territoryeditor-release#26]
Quando viene aggiunto un nuovo territorio, quindi uno che non è ancora mai stato assegnato, sull'app desktop viene visualizzato nella sezione giacenze, mentre sull'app mobile non viene visualizzato

**Comment by savio-99** [comment]
Il problema è già gestito dalla 1.0.5, perciò è possibile che ci sia un problema con i registri generati da te, però un territorio di base senza assegnazioni è in cima all'elenco.
Prova a controllare i registri.json per vedere che non ci sia registrazioni "vuote".

**Comment by Lukemoro01** [comment]
https://user-images.githubusercontent.com/53223843/187060963-5bfbc91c-1319-49f4-bd0f-e03879a54661.mp4

![image](https://user-images.githubusercontent.com/53223843/187061007-a2e3c367-a644-49ee-b22b-1d9e4d19e5d3.png)
