### ISSUE TITLE
Impossibile creare nuovi territori partendo dalle mappe

### ISSUE THREAD

**Issue by Lukemoro01** [savio-99/territoryeditor-release#30]
![image](https://github.com/savio-99/territoryeditor-release/assets/53223843/dd095e4e-0778-4bcb-9ca6-b032cd3afeb9)
![image](https://github.com/savio-99/territoryeditor-release/assets/53223843/5c37ece3-6fdb-4b27-b1e1-c1b9aba020f8)

Come si vede è scomparso il sito utilizzato di default per le mappe. cliccando ripristina torna, ma comunque non si possono generare mappe dalla pagina cartine & layout

**Comment by savio-99** [comment]
Stranamente a me funziona. Mi carichi il tuo file di log nella cartella di installazione (Cartella utente Windows/TerritoryEditor/Logs)?

**Comment by Lukemoro01** [comment]
hai ragione, funziona. Forse bastava riavviare il pc. Comunque non si è generato alcun log.
