### ISSUE TITLE
Indicare comune del territorio

### ISSUE THREAD

**Issue by Lukemoro01** [savio-99/territoryeditor-release#4]
Potrebbe essere piu chiaro leggere i dati se nella scheda "scadenze  giacenze" oltre a leggere il numero del territorio si potesse vedere anche il comune dello stesso, per facilitare le congregazioni che non usano una numerazione progressiva per tuto il territorio ma la usano comune per comune

**Comment by savio-99** [comment]
Risolto nella v1.3.3
