### ISSUE TITLE
Rendere piu intuitivi i label a fianco dei form di inserimento

### ISSUE THREAD

**Issue by Lukemoro01** [savio-99/territoryeditor-release#5]
![image](https://user-images.githubusercontent.com/53223843/132088429-ed37b63e-db6a-461d-b11c-c40517abae58.png)
Da un piccolo sondaggio risulta essere piu chiaro sostituire la dicitura "data ritiro" con la dicitura "data restituzione", come indicato da tabella a lato
![image](https://user-images.githubusercontent.com/53223843/132090393-96508ccc-8b08-4612-97e4-6a3725c7ba05.png)

**Comment by savio-99** [comment]
Risolto nella v1.3.3
