### ISSUE TITLE
Problemi modalità lite

### ISSUE THREAD

**Issue by Lukemoro01** [savio-99/territoryeditor-release#6]
In modalità Lite non è possibile salvare i dati aggiunti o modificarli. Inoltre risulta non viene mostrata la scheda "scadenze e giacenze", necessaria per poter assegnare un territorio che non sia stato predicato recentemente

**Comment by savio-99** [comment]
Risolto nella [v1.3.4](https://github.com/savio-99/territoryeditor-release/releases/tag/v1.3.4)
