### ISSUE TITLE
Grafico statistiche non visibile

### ISSUE THREAD

**Issue by Lukemoro01** [savio-99/territoryeditor-release#7]
Non è piu possibile visualizzare il grafico di percorrenza per semestre nella sezione Statistiche, come indicato nella foto
![image](https://user-images.githubusercontent.com/53223843/132810927-a7716439-f141-41a2-95e1-7c3f6b716c19.png)

**Comment by savio-99** [comment]
Risolto nella [v1.3.6](https://github.com/savio-99/territoryeditor-release/releases/tag/v1.3.6)
