### ISSUE TITLE
Problemi assegnazioni colori ai comuni

### ISSUE THREAD

**Issue by Lukemoro01** [savio-99/territoryeditor-release#9]
Quando vengono assegnati i colori primari ai comuni non si riesce piu a visualizzare le cartine del comune, tanto meno a generare i layout
Inoltre a volte acnhe usando colori secondari, quando si genera un layout viene cambiato in maniera casuale il colore

**Comment by savio-99** [comment]
Risolto nella [v1.3.9](https://github.com/savio-99/territoryeditor-release/releases/tag/v1.3.9)
